---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Project name
- type: datetime
  name: date
  label: Date
  hidden: true
  config:
    required: true
  default: now
- type: text
  name: ref
  label: ref
- type: text
  name: excerpt
  label: excerpt
- type: textarea
  name: ingress-text
  label: ingress-text
- type: file
  name: image
  label: image
