---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Project name
- type: file
  name: image
  label: Image
- type: textarea
  name: ingress-text
  label: Ingress
  config:
    required: true
    min: 10
    max: 300
- type: text
  name: excerpt
  label: Excerpt
  config:
    required: true
    min: 10
    max: 250
- type: text
  name: ref
  label: Translation Id
- type: datetime
  name: date
  label: Date
  hidden: true
  config:
    required: true
  default: now
