---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: ref
  label: ref
- type: text
  name: excerpt
  label: excerpt
- type: textarea
  name: ingress-text
  label: ingress-text
- type: file
  name: image
  label: image
